# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
domain="companionway.lab"
nodes=3
ipAddrPrefix = "10.0.30.2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.ssh.username = "wocos"
  #config.ssh.password = "socow42!"
  #config.vm.provision :shell, :inline => "apt-get update --fix-missing"
  config.vm.box = "precise64"
  numNodes = 4
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024]
  end
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
  (1..3).each do |i|
    nodeName = "node#{i}"
    config.vm.define nodeName do |node|
      node.vm.network :private_network, ip: "#{ipAddrPrefix}#{i}"
      node.vm.host_name = "#{nodeName}.#{domain}"
      node.vm.provider "virtualbox" do |v|
        #v.name = "myCluster: #{nodeName}"
        v.name = "#{nodeName}"
        v.customize ["modifyvm", :id, "--cpuexecutioncap", "50" ]
        v.memory = 512
        v.cpus = 2
      end
    end
  end
end

##############
#hosts = { 
#  "athos" => "192.168.66.10", 
#  "porthos" => "192.168.66.11", 
#  "aramis" => "192.168.66.12" 
#} 
#Vagrant.configure("2") do |config| 
#  config.vm.box = "precise64" 
#  config.vm.box_url = "http://files.vagrantup.com/precise64.box" 
#  hosts.each do |name, ip| 
#    config.vm.define name do |machine| 
#      machine.vm.network :private_network, ip: ip 
#      machine.vm.provider "virtualbox" do |v| 
#        v.name = name 
#      end 
#    end 
#  end 
#end
